friends/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from vk_friends_app import urls as vk_friends_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((vk_friends_urls, 'vk_friends_app'), namespace='friends')),
]

vk_friends_app/urls.py
from django.urls import path
from vk_friends_app.views import *


urlpatterns = [
    path('', first_view, name='first_view'),
    path('friends', friends_list, name='friends_list')
]

vk_friends_app/views.py
from django.shortcuts import render, redirect

from vk_friends_app.extra_functions import *


def first_view(request):
    if str((request.get_full_path())).find('logout') != -1:
        try:
            request.session.delete_test_cookie()
        except KeyError:
            print('Already logout')

    if request.session.test_cookie_worked():
        return redirect('https://oauth.vk.com/authorize?client_id=6758982&display=page&'
                        'redirect_uri=http://127.0.0.1:8000/friends&'
                        'scope=friends&response_type=code&v=5.92')
    else:
        return render(request, 'vk_friends_app/button.html')


def friends_list(request):
    code = str(request.get_full_path()).split('?code=')[-1] # get code for token

    token, user_id, token_lifetime = get_token(code)
    if not token:
        return redirect('/')

    user_first_name, user_last_name = get_user_info(token, user_id)
    username = user_first_name + ' ' + user_last_name
    f_list = get_user_friends(token, user_id)

    request.session.set_test_cookie()

    data = {'user': username,
            'friends': f_list}

    return render(request,'vk_friends_app/friends.html', data)

vk_friends_app/templates/vk_friends_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
    />
  </head>

  <body>
    <main>
      {% block content %}
      {% endblock %}
    </main>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
	  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	  crossorigin="anonymous"
    />
  </body>
</html>

vk_friends_app/templates/vk_friends_app/button.html
{% extends 'vk_friends_app/base.html' %}

{% load static %}

{% block content %}

<div class="p-0 mb-0 text-white">
  <div class="row">
    <a href="https://oauth.vk.com/authorize?client_id=6758982&display=page&redirect_uri=http://127.0.0.1:8000/friends&scope=friends&response_type=code&v=5.92">
      <button type="button" class="btn btn-info"  type="submit" value="Submit" 
              style="position: absolute; top: 50%;left: 50%;transform: translate(-50%,-50%);">    
        <p class="text-center">
          <div class="col"> АВТОРИЗАЦИЯ </div>
        </p>    
      </button>
    </a>
  </div>
</div>

{% endblock %}

vk_friends_app/templates/vk_friends_app/friends.html
{% extends 'vk_friends_app/base.html' %}

{% load static %}

{% block content %}

<div class="p-0 mb-2 mt-5 text-info">
    <div class="row">
      <div class="col"><p class="text-center"> Это вы: </p></div>  
    </div>
</div>

<div class="p-0 mb-0 text-dark">
    <div class="row">
      <div class="col"><p class="text-center"> {{ user }} </p></div>  
    </div>
</div>

<div class="p-0 mb-0 mt-5 text-info">
    <div class="row">
      <div class="col"><p class="text-center"> А это 5 ваших случайных друзей: </p></div>  
    </div>
</div>

{% for friend in friends %}
  <div class="p-0 mb-0 text-dark">
      <div class="row">
        <div class="col">
          <p class="text-center"> {{ friend }} </p>
        </div>  
      </div>
  </div>
{% endfor %}

<div class="p-0 mb-0 text-white">
  <div class="row">
    <div class="col my-4">
      <p class="text-center"> 
        <button type="button" class="btn btn-info" value="Submit" id="exittt">    
          Выход  
        </button>
      </p>
    </div>
  </div>
</div>

<script type="application/javascript">
    (function (window, document) {
      document.addEventListener('DOMContentLoaded', function () {
        var control = document.getElementById('exittt');
        control.addEventListener('click', function (event) {
          window.location.href = "{% url 'friends:first_view' %}?logout"
        })
      })
    })(window, document);
</script>

{% endblock %}
